name: dormly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  intl_phone_number_input: ^0.7.3+1
  provider: ^6.0.5
  shared_preferences: ^2.5.2
  flutter_carousel_slider: ^1.1.0
  http: ^1.0.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
